/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.lthn.sdk.apis.RunnerApi
import ai.lthn.sdk.models.GetHealth429Response
import ai.lthn.sdk.models.GetV1RunnerModels200Response
import ai.lthn.sdk.models.PostV1RunnerChat200Response
import ai.lthn.sdk.models.PostV1RunnerChatRequest
import ai.lthn.sdk.models.PostV1RunnerGenerateRequest

class RunnerApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RunnerApi
        //val apiInstance = RunnerApi()

        // to test getV1RunnerModels
        should("test getV1RunnerModels") {
            // uncomment below to test getV1RunnerModels
            //val result : GetV1RunnerModels200Response = apiInstance.getV1RunnerModels()
            //result shouldBe ("TODO")
        }

        // to test postV1RunnerChat
        should("test postV1RunnerChat") {
            // uncomment below to test postV1RunnerChat
            //val postV1RunnerChatRequest : PostV1RunnerChatRequest =  // PostV1RunnerChatRequest | 
            //val result : PostV1RunnerChat200Response = apiInstance.postV1RunnerChat(postV1RunnerChatRequest)
            //result shouldBe ("TODO")
        }

        // to test postV1RunnerGenerate
        should("test postV1RunnerGenerate") {
            // uncomment below to test postV1RunnerGenerate
            //val postV1RunnerGenerateRequest : PostV1RunnerGenerateRequest =  // PostV1RunnerGenerateRequest | 
            //val result : PostV1RunnerChat200Response = apiInstance.postV1RunnerGenerate(postV1RunnerGenerateRequest)
            //result shouldBe ("TODO")
        }

    }
}
