/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.lthn.sdk.models.GetV1RunnerModels200ResponseData

class GetV1RunnerModels200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetV1RunnerModels200ResponseData
        //val modelInstance = GetV1RunnerModels200ResponseData()

        // to test the property `models`
        should("test models") {
            // uncomment below to test the property
            //modelInstance.models shouldBe ("TODO")
        }

    }
}
