/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.lthn.sdk.models.PostV1RunnerChatRequest
import ai.lthn.sdk.models.PostV1RunnerChatRequestMessagesInner

class PostV1RunnerChatRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostV1RunnerChatRequest
        //val modelInstance = PostV1RunnerChatRequest()

        // to test the property `messages`
        should("test messages") {
            // uncomment below to test the property
            //modelInstance.messages shouldBe ("TODO")
        }

    }
}
