/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ai.lthn.sdk.models.PostV1RunnerChat200ResponseData

class PostV1RunnerChat200ResponseDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of PostV1RunnerChat200ResponseData
        //val modelInstance = PostV1RunnerChat200ResponseData()

        // to test the property `reply`
        should("test reply") {
            // uncomment below to test the property
            //modelInstance.reply shouldBe ("TODO")
        }

    }
}
