/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param duration 
 * @param page 
 * @param perPage 
 * @param requestId 
 * @param total 
 */
@Serializable

data class Meta (

    @SerialName(value = "duration")
    val duration: kotlin.String? = null,

    @SerialName(value = "page")
    val page: kotlin.Int? = null,

    @SerialName(value = "per_page")
    val perPage: kotlin.Int? = null,

    @SerialName(value = "request_id")
    val requestId: kotlin.String? = null,

    @SerialName(value = "total")
    val total: kotlin.Int? = null

) {


}

