/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "DuplicatedCode",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "RemoveRedundantCallsOfConversionMethods",
    "REDUNDANT_CALL_OF_CONVERSION_METHOD",
    "RedundantUnitReturnType",
    "RemoveEmptyClassBody",
    "UnnecessaryVariable",
    "UnusedImport",
    "UnnecessaryVariable",
    "unused"
)

package ai.lthn.sdk.models

import ai.lthn.sdk.models.Error
import ai.lthn.sdk.models.Meta
import ai.lthn.sdk.models.PostV1RunnerChat200ResponseData

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param success 
 * @param `data` 
 * @param error 
 * @param meta 
 */
@Serializable

data class PostV1RunnerChat200Response (

    @SerialName(value = "success")
    val success: kotlin.Boolean,

    @SerialName(value = "data")
    val `data`: PostV1RunnerChat200ResponseData? = null,

    @SerialName(value = "error")
    val error: Error? = null,

    @SerialName(value = "meta")
    val meta: Meta? = null

) {


}

